# Generated by Django 5.2.6 on 2025-10-04 21:56

import logims.drivers.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='nid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drivercontract',
            name='file',
            field=models.FileField(upload_to=logims.drivers.utils.driver_document_path),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='file',
            field=models.FileField(upload_to=logims.drivers.utils.driver_document_path),
        ),
        migrations.AlterField(
            model_name='drivernationalid',
            name='file',
            field=models.FileField(upload_to=logims.drivers.utils.driver_document_path),
        ),
        migrations.AlterField(
            model_name='drivervehiclelicense',
            name='file',
            field=models.FileField(upload_to=logims.drivers.utils.driver_document_path),
        ),
    ]
