# Generated by Django 5.2.6 on 2025-10-11 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_nid_alter_driver_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='agency_share',
            field=models.FloatField(blank=True, help_text='Agency share as decimal (e.g., 0.1 for 10%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='driver',
            name='insurance',
            field=models.FloatField(blank=True, help_text='Insurance amount', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
