# Generated by Django 5.2.6 on 2025-10-15 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_agency_share_driver_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='agency_share',
            field=models.FloatField(blank=True, help_text='Agency share as percentage (e.g., 15 for 15%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
