# Generated by Django 5.2.6 on 2025-10-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_alter_driver_agency_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='reports_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
