# Generated by Django 5.2.6 on 2025-11-19 15:37

import logims.drivers.utils
import logims.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_driver_email_driver_reports_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivercontract',
            name='file',
            field=models.FileField(storage=logims.storage_backends.R2MediaStorage(), upload_to=logims.drivers.utils.driver_document_path),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='file',
            field=models.FileField(storage=logims.storage_backends.R2MediaStorage(), upload_to=logims.drivers.utils.driver_document_path),
        ),
        migrations.AlterField(
            model_name='drivernationalid',
            name='file',
            field=models.FileField(storage=logims.storage_backends.R2MediaStorage(), upload_to=logims.drivers.utils.driver_document_path),
        ),
        migrations.AlterField(
            model_name='drivervehiclelicense',
            name='file',
            field=models.FileField(storage=logims.storage_backends.R2MediaStorage(), upload_to=logims.drivers.utils.driver_document_path),
        ),
    ]
