# Generated by Django 5.2.6 on 2025-12-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_supervisor_remove_driver_reports_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='agency_share',
        ),
    ]
