# Generated by Django 5.2.6 on 2025-12-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_remove_driver_agency_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
