# Generated by Django 5.2.6 on 2025-12-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_alter_driver_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='phone',
            field=models.CharField(db_index=True, max_length=16),
        ),
    ]
