# Generated by Django 5.2.6 on 2025-10-24 17:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_add_uber_eats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('payments', 'Payments/Payroll'), ('trips', 'Trip Details')], help_text='Type of data in the file (Excel or CSV)', max_length=20)),
                ('file', models.FileField(upload_to='file_uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'csv'])])),
                ('from_date', models.DateField(help_text='Start date for the data period')),
                ('to_date', models.DateField(help_text='End date for the data period')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_records_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_uuid', models.CharField(db_index=True, max_length=100)),
                ('driver_first_name', models.CharField(max_length=255)),
                ('driver_last_name', models.CharField(max_length=255)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promotions', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refunds_and_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payouts', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bank_transfer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_collected', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fare_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tips', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_deductions', models.DecimalField(blank=True, decimal_places=2, help_text='Total deductions (tax + agency share + insurance)', max_digits=10, null=True)),
                ('tax_deduction', models.DecimalField(blank=True, decimal_places=2, help_text='Tax amount deducted', max_digits=10, null=True)),
                ('agency_share_deduction', models.DecimalField(blank=True, decimal_places=2, help_text='Agency share amount deducted', max_digits=10, null=True)),
                ('insurance_deduction', models.DecimalField(blank=True, decimal_places=2, help_text='Insurance amount deducted', max_digits=10, null=True)),
                ('final_net_earnings', models.DecimalField(blank=True, decimal_places=2, help_text='Final earnings after all deductions', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='data_imports.fileupload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tax configuration name (e.g., 'Income Tax', 'Social Security')", max_length=100)),
                ('tax_rate', models.DecimalField(decimal_places=2, help_text='Tax rate as percentage (e.g., 15.5 for 15.5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this tax covers', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_configurations', to='companies.company')),
            ],
            options={
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TripRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_uuid', models.CharField(db_index=True, max_length=100)),
                ('driver_uuid', models.CharField(db_index=True, max_length=100)),
                ('driver_first_name', models.CharField(max_length=255)),
                ('driver_last_name', models.CharField(max_length=255)),
                ('vehicle_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('license_plate', models.CharField(blank=True, max_length=50, null=True)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('order_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('destination_address', models.TextField(blank=True, null=True)),
                ('trip_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('trip_status', models.CharField(blank=True, max_length=100, null=True)),
                ('order_submitted_time', models.DateTimeField(blank=True, null=True)),
                ('trip_start_time', models.DateTimeField(blank=True, null=True)),
                ('vehicle_location_at_assignment', models.TextField(blank=True, null=True)),
                ('fare_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trip_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_records', to='data_imports.fileupload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['company', 'file_type'], name='data_import_company_d1e5e1_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['status'], name='data_import_status_29fe4e_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['from_date', 'to_date'], name='data_import_from_da_c0570a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['driver_uuid'], name='data_import_driver__c2950e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['file_upload'], name='data_import_file_up_402f00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxconfiguration',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='triprecord',
            index=models.Index(fields=['trip_uuid'], name='data_import_trip_uu_561086_idx'),
        ),
        migrations.AddIndex(
            model_name='triprecord',
            index=models.Index(fields=['driver_uuid'], name='data_import_driver__4da53f_idx'),
        ),
        migrations.AddIndex(
            model_name='triprecord',
            index=models.Index(fields=['file_upload'], name='data_import_file_up_693a61_idx'),
        ),
        migrations.AddIndex(
            model_name='triprecord',
            index=models.Index(fields=['order_time'], name='data_import_order_t_05fb8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='triprecord',
            unique_together={('file_upload', 'trip_uuid')},
        ),
    ]
