# Generated by Django 5.2.6 on 2025-10-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_imports', '0002_add_uber_eats_tax_config'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='triprecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='triprecord',
            name='trip_uuid',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
