# Generated by Django 5.2.6 on 2025-11-19 15:37

import django.core.validators
import logims.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_imports', '0003_alter_triprecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(storage=logims.storage_backends.R2MediaStorage(), upload_to='file_uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'csv'])]),
        ),
    ]
