# Generated by Django 5.2.6 on 2025-12-05 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_imports', '0004_alter_fileupload_file'),
        ('drivers', '0009_alter_driver_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='applied_agency_share_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agency share percentage used at calculation time', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='applied_insurance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Insurance amount used at calculation time', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='applied_tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total tax rate used at calculation time (sum of all active tax rates)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='calculated_at',
            field=models.DateTimeField(blank=True, help_text='When calculations were last performed', null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='calculation_version',
            field=models.CharField(default='1.0', help_text='Version of calculation logic used', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Foreign key to Driver model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='driver_id_at_calculation',
            field=models.IntegerField(blank=True, help_text='Driver ID at time of calculation', null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='supervisor_id_at_calculation',
            field=models.IntegerField(blank=True, help_text='Supervisor ID at time of calculation', null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='supervisor_name_at_calculation',
            field=models.CharField(blank=True, help_text='Supervisor name at time of calculation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='triprecord',
            name='calculated_at',
            field=models.DateTimeField(blank=True, help_text='When calculations were last performed', null=True),
        ),
        migrations.AddField(
            model_name='triprecord',
            name='calculation_version',
            field=models.CharField(default='1.0', help_text='Version of calculation logic used', max_length=50),
        ),
        migrations.AddField(
            model_name='triprecord',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Foreign key to Driver model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_records', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='triprecord',
            name='driver_id_at_calculation',
            field=models.IntegerField(blank=True, help_text='Driver ID at time of calculation', null=True),
        ),
        migrations.AddField(
            model_name='triprecord',
            name='supervisor_id_at_calculation',
            field=models.IntegerField(blank=True, help_text='Supervisor ID at time of calculation', null=True),
        ),
        migrations.AddField(
            model_name='triprecord',
            name='supervisor_name_at_calculation',
            field=models.CharField(blank=True, help_text='Supervisor name at time of calculation', max_length=255, null=True),
        ),
    ]
