# Generated by Django 5.2.6 on 2026-01-21 17:25

import django.core.validators
import django.db.models.deletion
import logims.storage_backends
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_add_uber_eats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload_id', models.IntegerField(db_index=True, help_text='ID of the file upload (may reference deleted file)')),
                ('file_title', models.CharField(help_text='Title of the file upload at time of action', max_length=255)),
                ('file_type', models.CharField(choices=[('payments', 'Payments/Payroll'), ('trips', 'Trip Details'), ('expenses', 'Expenses'), ('contracts', 'Contracts'), ('other', 'Other')], help_text='Type of file at time of action', max_length=20)),
                ('action', models.CharField(help_text="Action performed (e.g., 'created', 'updated', 'deleted', 'processing_started', 'processing_completed', 'processing_failed')", max_length=50)),
                ('user_id', models.IntegerField(blank=True, db_index=True, help_text='ID of the user who performed the action (may reference deleted user)', null=True)),
                ('username', models.CharField(blank=True, help_text='Username at time of action', max_length=150, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['file_upload_id', 'timestamp'], name='uploads_fil_file_up_9b5c7f_idx'), models.Index(fields=['action'], name='uploads_fil_action_74eea1_idx'), models.Index(fields=['user_id', 'timestamp'], name='uploads_fil_user_id_c7baf8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name', max_length=100, unique=True)),
                ('is_predefined', models.BooleanField(default=False, help_text='Whether this is a predefined system tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='uploads_tag_name_21eab7_idx'), models.Index(fields=['is_predefined'], name='uploads_tag_is_pred_dbd22f_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or description of the document', max_length=255)),
                ('file_type', models.CharField(choices=[('payments', 'Payments/Payroll'), ('trips', 'Trip Details'), ('expenses', 'Expenses'), ('contracts', 'Contracts'), ('other', 'Other')], help_text='Type of document', max_length=20)),
                ('file', models.FileField(storage=logims.storage_backends.R2MediaStorage(), upload_to='file_uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv', 'jpg', 'jpeg', 'png', 'zip', 'rar'])])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_records_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for categorizing documents', related_name='file_uploads', to='uploads.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentUploadMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, help_text='Start date for the period (for payments and trips)', null=True)),
                ('to_date', models.DateField(blank=True, help_text='End date for the period (for payments and trips)', null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount (for expenses)', max_digits=10, null=True)),
                ('company', models.ForeignKey(blank=True, help_text='Company (for payments and trips)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_metadata', to='companies.company')),
                ('file_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='uploads.fileupload')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'from_date', 'to_date'], name='uploads_doc_company_196bc8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['file_type'], name='uploads_fil_file_ty_9d9c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['status'], name='uploads_fil_status_1faa00_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['created_at'], name='uploads_fil_created_ad744b_idx'),
        ),
    ]
