# Generated by Django 5.2.6 on 2026-01-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuploadmetadata',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount', max_digits=10, null=True),
        ),
    ]
