# Generated by Django 5.2.6 on 2026-01-21 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0010_alter_driver_phone_number_alter_supervisor_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_uuid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('driver_uuid', models.CharField(db_index=True, max_length=100)),
                ('driver_first_name', models.CharField(max_length=255)),
                ('driver_last_name', models.CharField(max_length=255)),
                ('vehicle_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('license_plate', models.CharField(blank=True, max_length=50, null=True)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('order_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('destination_address', models.TextField(blank=True, null=True)),
                ('trip_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('trip_status', models.CharField(blank=True, max_length=100, null=True)),
                ('order_submitted_time', models.DateTimeField(blank=True, null=True)),
                ('trip_start_time', models.DateTimeField(blank=True, null=True)),
                ('vehicle_location_at_assignment', models.TextField(blank=True, null=True)),
                ('fare_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trip_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('calculation_version', models.CharField(default='1.0', help_text='Version of calculation logic used', max_length=50)),
                ('calculated_at', models.DateTimeField(blank=True, help_text='When calculations were last performed', null=True)),
                ('driver_id_at_calculation', models.IntegerField(blank=True, help_text='Driver ID at time of calculation', null=True)),
                ('supervisor_id_at_calculation', models.IntegerField(blank=True, help_text='Supervisor ID at time of calculation', null=True)),
                ('supervisor_name_at_calculation', models.CharField(blank=True, help_text='Supervisor name at time of calculation', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, help_text='Foreign key to Driver model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_records', to='drivers.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
