# Generated by Django 5.2.6 on 2026-01-21 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprecord',
            name='file_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_records', to='uploads.fileupload'),
        ),
        migrations.AddIndex(
            model_name='triprecord',
            index=models.Index(fields=['trip_uuid'], name='trips_tripr_trip_uu_ae3976_idx'),
        ),
        migrations.AddIndex(
            model_name='triprecord',
            index=models.Index(fields=['driver_uuid'], name='trips_tripr_driver__0733c4_idx'),
        ),
        migrations.AddIndex(
            model_name='triprecord',
            index=models.Index(fields=['file_upload'], name='trips_tripr_file_up_1659bd_idx'),
        ),
        migrations.AddIndex(
            model_name='triprecord',
            index=models.Index(fields=['order_time'], name='trips_tripr_order_t_5a64d4_idx'),
        ),
        migrations.AddIndex(
            model_name='triprecord',
            index=models.Index(fields=['driver_id_at_calculation'], name='trips_tripr_driver__2ae216_idx'),
        ),
        migrations.AddIndex(
            model_name='triprecord',
            index=models.Index(fields=['supervisor_id_at_calculation'], name='trips_tripr_supervi_600916_idx'),
        ),
        migrations.AddIndex(
            model_name='triprecord',
            index=models.Index(fields=['trip_status'], name='trips_tripr_trip_st_bac61d_idx'),
        ),
        migrations.AddIndex(
            model_name='triprecord',
            index=models.Index(fields=['file_upload', 'driver_uuid'], name='trips_tripr_file_up_49a667_idx'),
        ),
        migrations.AddIndex(
            model_name='triprecord',
            index=models.Index(fields=['driver_id_at_calculation', 'file_upload'], name='trips_tripr_driver__1cb5c8_idx'),
        ),
    ]
