# Generated by Django 5.2.6 on 2026-01-21 17:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0010_alter_driver_phone_number_alter_supervisor_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tax configuration name (e.g., 'Income Tax', 'Social Security')", max_length=100)),
                ('tax_rate', models.DecimalField(decimal_places=2, help_text='Tax rate as percentage (e.g., 15.5 for 15.5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this tax covers', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_uuid', models.CharField(db_index=True, max_length=100)),
                ('driver_first_name', models.CharField(max_length=255)),
                ('driver_last_name', models.CharField(max_length=255)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promotions', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refunds_and_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payouts', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bank_transfer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_collected', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fare_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tips', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_deductions', models.DecimalField(blank=True, decimal_places=2, help_text='Total deductions (tax + agency share + insurance)', max_digits=10, null=True)),
                ('tax_deduction', models.DecimalField(blank=True, decimal_places=2, help_text='Tax amount deducted', max_digits=10, null=True)),
                ('agency_share_deduction', models.DecimalField(blank=True, decimal_places=2, help_text='Agency share amount deducted', max_digits=10, null=True)),
                ('insurance_deduction', models.DecimalField(blank=True, decimal_places=2, help_text='Insurance amount deducted', max_digits=10, null=True)),
                ('final_net_earnings', models.DecimalField(blank=True, decimal_places=2, help_text='Final earnings after all deductions', max_digits=10, null=True)),
                ('calculation_version', models.CharField(default='1.0', help_text='Version of calculation logic used', max_length=50)),
                ('calculated_at', models.DateTimeField(blank=True, help_text='When calculations were last performed', null=True)),
                ('applied_tax_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Total tax rate used at calculation time (sum of all active tax rates)', max_digits=5, null=True)),
                ('applied_agency_share_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Agency share percentage used at calculation time', max_digits=5, null=True)),
                ('applied_insurance_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Insurance amount used at calculation time', max_digits=10, null=True)),
                ('driver_id_at_calculation', models.IntegerField(blank=True, help_text='Driver ID at time of calculation', null=True)),
                ('supervisor_id_at_calculation', models.IntegerField(blank=True, help_text='Supervisor ID at time of calculation', null=True)),
                ('supervisor_name_at_calculation', models.CharField(blank=True, help_text='Supervisor name at time of calculation', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, help_text='Foreign key to Driver model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='drivers.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
