# Generated by Django 5.2.6 on 2026-01-21 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_add_uber_eats'),
        ('payroll', '0001_initial'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='file_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='uploads.fileupload'),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_configurations', to='companies.company'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['driver_uuid'], name='payroll_pay_driver__978d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['file_upload'], name='payroll_pay_file_up_df1ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['driver_id_at_calculation'], name='payroll_pay_driver__3249d7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['supervisor_id_at_calculation'], name='payroll_pay_supervi_4ecebc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['file_upload', 'driver_uuid'], name='payroll_pay_file_up_f8e5b8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['driver_id_at_calculation', 'file_upload'], name='payroll_pay_driver__22fc0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxconfiguration',
            unique_together={('company', 'name')},
        ),
    ]
