# Generated by Django 5.2.6 on 2025-10-29 14:05

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0005_driver_email_driver_reports_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]), blank=True, default=list, help_text='List of admin email addresses to receive notifications', size=None)),
                ('warning_days_before_expiry', models.PositiveIntegerField(default=30, help_text='Number of days before expiration to send warning notification', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('from_email', models.EmailField(blank=True, help_text='From email address (leave blank to use default)', max_length=254)),
                ('email_subject_prefix', models.CharField(default='[LogiMS]', help_text='Prefix for email subject lines', max_length=50)),
                ('notify_on_warning', models.BooleanField(default=True, help_text='Send notifications when documents are about to expire')),
                ('notify_on_expired', models.BooleanField(default=True, help_text='Send notifications when documents have expired')),
                ('notify_driver', models.BooleanField(default=True, help_text='Send notification to driver (if email available)')),
                ('notify_admins', models.BooleanField(default=True, help_text='Send notification to admin emails')),
                ('notify_national_id', models.BooleanField(default=True, help_text='Send notifications for National ID documents')),
                ('notify_license', models.BooleanField(default=True, help_text='Send notifications for License documents')),
                ('notify_vehicle_license', models.BooleanField(default=True, help_text='Send notifications for Vehicle License documents')),
                ('notify_contract', models.BooleanField(default=True, help_text='Send notifications for Contract documents')),
                ('check_schedule_cron', models.CharField(default='0 9 * * *', help_text='Cron expression for check schedule (default: daily at 9 AM)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable all notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Configuration',
                'verbose_name_plural': 'Notification Configuration',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('warning', 'Warning (About to Expire)'), ('expired', 'Expired')], help_text='Type of notification', max_length=20)),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('license', 'License'), ('vehicle_license', 'Vehicle License'), ('contract', 'Contract')], help_text='Type of document', max_length=20)),
                ('document_id', models.PositiveIntegerField(help_text='ID of the specific document (varies by type)')),
                ('expiry_date', models.DateField(help_text='Expiry date of the document at time of notification')),
                ('recipients', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), default=list, help_text='List of email addresses that received this notification', size=None)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if notification failed')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the notification was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', 'document_type', 'notification_type'], name='notificatio_driver__b20f76_idx'), models.Index(fields=['created_at'], name='notificatio_created_01830a_idx'), models.Index(fields=['status'], name='notificatio_status_a242db_idx')],
            },
        ),
    ]
