# Generated by Django 5.2.6 on 2025-10-31 21:31

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationconfig',
            name='admin_digest_cooldown_hours',
            field=models.PositiveIntegerField(default=24, help_text='Hours to wait before sending duplicate admin digest emails', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='notification_cooldown_days',
            field=models.PositiveIntegerField(default=7, help_text='Days to wait before sending duplicate individual notifications (NOTE: Each document gets max 2 emails total)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='admin_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]), blank=True, default=list, help_text='List of email addresses to receive notifications (can be any valid email)', size=None),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='document_type',
            field=models.CharField(choices=[('national_id', 'National ID'), ('license', 'License'), ('vehicle_license', 'Vehicle License'), ('contract', 'Contract'), ('admin_digest', 'Admin Digest Email')], help_text='Type of document', max_length=20),
        ),
    ]
