# Generated by Django 5.2.6 on 2025-11-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationconfig_admin_digest_cooldown_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationconfig',
            name='check_schedule_cron',
            field=models.CharField(default='0 9 * * *', help_text="Cron expression for check schedule (default: daily at 9 AM). Auto-syncs with Celery Beat periodic task. Format: 'minute hour day month day_of_week'", max_length=100),
        ),
    ]
