# Generated by Django 5.2.6 on 2025-09-28 19:21

from django.db import migrations
from django.core.files import File
import os

def create_initial_companies(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    Company.objects.get_or_create(code="uber_eats", name="Uber Eats", is_active=True, logo="logos/uber_eats.jpeg")

def remove_initial_companies(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    Company.objects.filter(code="uber_eats").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_companies),
    ]
